### ISSUE TITLE
When editing `tablesInfos.yml` from script, integers are passed as strings

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/pinosync#3]
As the picture shows, fields which should be integers are instead saved as strings by the script. This produces an error.

![Screenshot from 2023-05-06 16-58-06](https://user-images.githubusercontent.com/42862428/236631916-d77d3f71-9255-4d81-84ef-07ead05eb76b.png)

**Comment by xplosionmind** [comment]
This issue might not be relevant, since I thought this was the cause of #4, but it is not. Maybe even if a number is passed as a string rather than an integer it still is ok for Baserow.

**Comment by 2ale2** [comment]
Both integers and strings are fine since values are obtained like this:

`id=int(tables_infos["id"])`
`view_id=int(tables_infos["view_id"])`
