### ISSUE TITLE
Syntax error in CSV file

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/pinosync#6]
As GitHub shows, there is a syntax error in [this CSV file](https://github.com/scambifestival/scambi.org/blob/main/data/2021-labs.csv).

![Screenshot from 2023-05-18 12-12-49](https://github.com/scambifestival/pinosync/assets/42862428/822b760e-a428-4e2c-856c-dd11d910692a)

**Comment by 2ale2** [comment]
GitHub is right: the description field in line 5 contains the sequence `",`, but it isn't the end of the field, so this triggers an error.

I think I'll change any quotes inside a field with a single quote or with another equivalent. Alternatively, changing neutral double quotes with left and right double quotes to indicate the start and the end of a field can be considered if it's suitable with other configurations (e.g. Eleventy).

**Comment by xplosionmind** [comment]
I think taking advantage of the [Python CSV library](https://docs.python.org/3/library/csv.html) might help you in avoiding format errors.

[More info](https://realpython.com/python-csv)

**Comment by 2ale2** [comment]
Personally (and I am the only one using the script so far) I believe it is better to have a reliable and bug-free solution, accepting a trade-off giving up some RAM and efficiency.

Anyway, I trouts your choice.

I would be glad not having to stop at every single specific problem that a library could handle with no problem (that is what libraries exist for…).

**Comment by 2ale2** [comment]
@xplosionmind i don't know why u edited my comment instead of replying. btw no tests have been made on the script as you wanted, even if I strongly recommended it, so now we must take what comes

**Comment by 2ale2** [comment]
Fixed issue: double quotes inside a field are replaced with `“` and `”` (directional double quotes), removing bug sequences `",`. Delimiters are still universal double quotes (`"`). Changes will be committed once I'll fix the other issue.
