### ISSUE TITLE
Missing data in arrays within CSV files

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/pinosync#7]
When there are multiple comma-separated values, only the first one is added to the CSV file. In the bug example below, the fields `giorni` are incomplete in the parsed csv.

Original table on Pino:
![Screenshot from 2023-05-27 17-14-59](https://github.com/scambifestival/pinosync/assets/42862428/5493f461-0f51-46f3-831f-ce7d77700cc3)

---

`2021-labs.csv` on scambi.org/data on GitHub:
![Screenshot from 2023-05-27 17-15-25](https://github.com/scambifestival/pinosync/assets/42862428/86ad233e-7a08-4f7c-8747-ae6c2ef20e68)

**Comment by 2ale2** [comment]
Values of a multiple selection column will be separated by a comma. Further infos soon.

**Comment by 2ale2** [comment]
Issue has been fixed. 

Here is an example of how an output file looks like now:

**CSV format**
![image](https://github.com/scambifestival/pinosync/assets/76873631/8513276d-396d-457a-8870-748088da5a74)

**JSON format**
![image](https://github.com/scambifestival/pinosync/assets/76873631/e27641cf-f0d8-4ed4-9578-c11556c9aefa)

_Note_: the examples do not show the complete files

**Comment by xplosionmind** [comment]
In JSON, wouldn’t it be possible to have the array formatted as a proper array (eg. `[27,28,29]`) instead of having it formatted as a string?

**Comment by 2ale2** [comment]
@xplosionmind it is I think, I'll work on it

**Comment by 2ale2** [comment]
@xplosionmind Issue is fixed and JSON format for arrays has been properly edited with last commit.
